### ISSUE TITLE
varnishtop and varnishist segfault

### ISSUE THREAD

**Issue by githubcdr** [Hermsi1337/docker-varnish#2]
Hi,

I noticed that the commands varnishtop and varnishist give segfaults on the 6.1.1 release, when running "varnishtop -1" it works.

Are you able to reproduce these errors?

Regards, cDR

**Comment by Hermsi1337** [comment]
Hey @githubcdr ,

thanks for reporting, I can also reproduce this error with `6.1` and `6.0`.   

I've released a new tag and version - `6.2` - today. With this version there is no segfault when running `varnisthop` or similiar.   
If it's okay for you to use a `fresh` release of varnish, I'd recommend to use `6.2`.

The segfault in `6.0` and `6.1` seems like an issue of the `varnish`-package for `alpine`.   
I will try to create a small, `ubuntu`- or `debian`-based image, for those people who need access to `varnishtop` and/or `varnishhist` but don't want to use the latest `varnish`-version `6.2`.

Regards,   
Hermsi

**Comment by githubcdr** [comment]
Hi @Hermsi1337,


Thanks for your image and quick response, I will test the new release and let you know.

For a second I was suspecting container missing capabilities required for accessing shared memory but glad this bug is upstream :)

**Comment by githubcdr** [comment]
@Hermsi1337 ,

Varnishtop and varnishhist are both working in 6.2, thanks again.
