### ISSUE TITLE
Docker registry

### ISSUE THREAD

**Issue by githubcdr** [Hermsi1337/docker-varnish#5]
Hi Hermsi,

Any chance that you could upload this amazing image to other registries? quay, gh etc?

Docker is hating the end user and I just want to avoid them.

Also Varnish 7 got released ;)

**Comment by Hermsi1337** [comment]
Good idea (= 

https://quay.io/repository/hermsi1337/alpine-varnish?tab=tags

I'd appreciate your feedback as soon as you're using the quay image :3

**Comment by githubcdr** [comment]
Version 7.0 from quay running great!

Thanks :)
