### ISSUE TITLE
Release image for 7.0.2

### ISSUE THREAD

**Issue by muffl0n** [Hermsi1337/docker-varnish#8]
Varnish 7.0.2 was released "26 days ago". Strangely, the [last CI run one week ago](https://gitlab.com/hermsi1337/docker-varnish/-/pipelines/455296545) did not pick it up.

Could you give it another try?

Thank you very much!

**Comment by Hermsi1337** [comment]
Yikes, this is weird o.o

I've re-ran the CI. Version `7.0.2` should be released in no-time (= 


https://gitlab.com/hermsi1337/docker-varnish/-/jobs/2062133963



PS: Thanks for the hint!

**Comment by muffl0n** [comment]
Awesome! Thank you very much for the quick bump! :)
